name: Test training pipeline

# Cuándo se ejecuta:
# - en cada push a la rama main
# - en cada pull request hacia main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código del repo en la máquina virtual
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # 2. Instala Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Instala las dependencias del proyecto
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # 4. Corre el pipeline de entrenamiento
      - name: Ejecutar train.py
        run: |
          cd src
          python train.py
